### ISSUE TITLE
Dynamic imports?

### ISSUE THREAD

**Issue by zellwk** [elringus/imgit#16]
Possible to use dynamic imports with this with Astro? I tried and it got an error. Here's a quick screenshot. 

![CleanShot 2024-04-05 at 01 10 08](https://github.com/elringus/imgit/assets/3607637/eddcc81d-0bb5-4989-a7ba-0744a62fdaed)

**Comment by elringus** [comment]
Yes, here are the docs: https://imgit.dev/guide/asset-import
And here's a sample with Astro: https://github.com/elringus/imgit/blob/main/samples/astro/src/pages/import.astro

**Comment by zellwk** [comment]
Apparently I was using a wrong link. Thanks.
