### ISSUE TITLE
Image Paths

### ISSUE THREAD

**Issue by zellwk** [elringus/imgit#17]
Imgit with Astro fetches the file from the public directory. But there are many instances where I want to fetch images from the `/src/assets` directory instead (since I use Astro's image optimization tool as well). Is it possible to remove the `/public`?

```js
Example 
// Passed in value 
const test = await import('imgit:/asset/image.png') 

// Path used now
// /absolute-path-to-project/public/src/asset/image.png

// Preferred path 
// /absolute-path-to-project/src/asset/image.png
```

**Comment by elringus** [comment]
Sure, you can set the preferred root directory in the options:

https://github.com/elringus/imgit/blob/46f5765eb5fe5dcb4c5ba75322193fb4f7aecbb5/src/server/config/options.ts#L4-L7
